"""FLAC and MP3: four containers, one vocabulary (DESIGN §9, slice 53).

Until 1.0.0 this program could read and write two of them. Everything that was not `.m4a` was
opened as Opus, so a `.flac` raised inside `audio_length`, was caught, and came back `None` — and a
`None` length reads as "no match" while an empty quality reads as "unknown". Nothing failed and no
test noticed, because no test had ever seen a FLAC. **That is the defect these cases exist for**,
and the first one fails against 1.0.0.

The files are generated by ffmpeg at test time; no audio lives in the repository.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest
from mutagen.flac import FLAC
from mutagen.id3 import ID3
from mutagen.mp3 import MP3
from test_media import JPEG, make_plan

from noaap.tag import audio_length, audio_quality, kind, tag_file, tagged_lyrics

SECOND = ["-f", "lavfi", "-i", "sine=duration=1"]


def encode(path: Path, *args: str) -> Path:
    if not shutil.which("ffmpeg"):
        pytest.skip("ffmpeg not installed")
    subprocess.run(["ffmpeg", "-v", "error", *SECOND, *args, str(path)], check=True)
    return path


@pytest.fixture
def flac_file(tmp_path) -> Path:
    return encode(tmp_path / "t.flac", "-c:a", "flac", "-ar", "44100", "-metadata", "title=junk")


@pytest.fixture
def mp3_file(tmp_path) -> Path:
    return encode(tmp_path / "t.mp3", "-c:a", "libmp3lame", "-b:a", "192k", "-metadata", "title=junk")


@pytest.fixture
def opus_file(tmp_path) -> Path:
    return encode(tmp_path / "t.opus", "-c:a", "libopus")


@pytest.fixture
def m4a_file(tmp_path) -> Path:
    return encode(tmp_path / "t.m4a", "-c:a", "aac", "-b:a", "128k")


# -- reading -------------------------------------------------------------------------------------


def test_a_flac_has_a_length_and_a_quality(flac_file):
    """The regression, stated as plainly as it deserves: this answered None and {}."""
    assert audio_length(flac_file) == pytest.approx(1.0, abs=0.1)

    quality = audio_quality(flac_file)
    assert quality["codec"] == "flac"
    assert quality["sample_rate"] == 44100 and quality["channels"] == 1
    assert quality["bitrate"] > 0


def test_an_mp3_has_a_length_and_a_quality(mp3_file):
    assert audio_length(mp3_file) == pytest.approx(1.0, abs=0.2)

    quality = audio_quality(mp3_file)
    assert quality["codec"] == "mp3"
    assert quality["sample_rate"] == 44100
    assert 150_000 < quality["bitrate"] < 210_000


@pytest.mark.parametrize("name,expected", [("a.opus", "opus"), ("a.flac", "flac"), ("a.mp3", "mp3"),
                                           ("a.m4a", "mp4"), ("a.mp4", "mp4"), ("a.MP3", "mp3"),
                                           ("a.weird", "opus")])
def test_the_container_is_decided_in_one_place(name, expected):
    """An unknown suffix still reads as Opus — that is what every download is, and guessing
    anything else would turn an odd name into an unreadable file."""
    assert kind(Path(name)) == expected


def test_every_container_measures(opus_file, flac_file, mp3_file, m4a_file):
    for path in (opus_file, flac_file, mp3_file, m4a_file):
        assert audio_length(path) is not None, path.suffix
        assert audio_quality(path).get("codec"), path.suffix


def test_something_that_is_not_audio_is_still_an_unknown_not_a_crash(tmp_path):
    not_audio = tmp_path / "sleeve.flac"
    not_audio.write_bytes(b"<html>a consent page</html>")

    assert audio_length(not_audio) is None
    assert audio_quality(not_audio) == {}


# -- writing -------------------------------------------------------------------------------------


def test_a_flac_is_tagged_and_carries_its_cover(flac_file):
    plan = make_plan()
    tag_file(flac_file, plan, plan.tracks[0], cover=JPEG)

    tags = FLAC(flac_file)
    assert tags["title"] == ["T1"] and tags["artist"] == ["A1"]
    assert tags["albumartist"] == ["My Dark Lullabies"]
    assert tags["album"] == ["Vol. 1 - Heavy Sleeping"]
    assert tags["tracknumber"] == ["1"] and tags["tracktotal"] == ["2"]
    assert tags["compilation"] == ["1"]
    assert len(tags.pictures) == 1 and tags.pictures[0].data == JPEG
    assert tags.pictures[0].type == 3


def test_an_mp3_is_tagged_and_carries_its_cover(mp3_file):
    plan = make_plan()
    tag_file(mp3_file, plan, plan.tracks[0], cover=JPEG)

    tags = ID3(mp3_file)
    assert tags["TIT2"].text == ["T1"] and tags["TPE1"].text == ["A1"]
    assert tags["TPE2"].text == ["My Dark Lullabies"]
    assert tags["TALB"].text == ["Vol. 1 - Heavy Sleeping"]
    assert tags["TRCK"].text == ["1/2"], "ID3 counts within the total, in one frame"
    assert tags["TCMP"].text == ["1"]
    assert tags["APIC:Cover"].data == JPEG
    assert tags["TXXX:source"].text == [plan.source_url], "not COMM: that is where people keep notes"


def test_a_disc_number_is_written_only_when_there_is_more_than_one(mp3_file, flac_file):
    one, many = make_plan(), make_plan(discs=2)

    tag_file(mp3_file, one, one.tracks[0])
    tag_file(flac_file, one, one.tracks[0])
    assert "TPOS" not in ID3(mp3_file) and "discnumber" not in FLAC(flac_file)
    assert "disctotal" not in FLAC(flac_file), "nor a count of discs there is one of"

    tag_file(mp3_file, many, many.tracks[1])
    tag_file(flac_file, many, many.tracks[1])
    assert ID3(mp3_file)["TPOS"].text == ["2/2"], "ID3 counts within the total, in one frame"
    assert FLAC(flac_file)["discnumber"] == ["2"] and FLAC(flac_file)["disctotal"] == ["2"]


def test_lyrics_are_written_and_read_back_in_both(flac_file, mp3_file):
    plan = make_plan()
    words = "[00:01.00] a line\n[00:02.00] and another"

    for path in (flac_file, mp3_file):
        tag_file(path, plan, plan.tracks[0], lyrics=words)
        assert tagged_lyrics(path) == words, path.suffix


# -- a file we did not make -----------------------------------------------------------------------


def with_history(path: Path) -> Path:
    """What a folder someone has been keeping looks like: fields this program does not model."""
    if kind(path) == "mp3":
        from mutagen.id3 import TBPM, TCOM, TSRC, TXXX, USLT
        tags = ID3(path) if MP3(path).tags else ID3()
        tags.add(TCOM(encoding=3, text=["A composer"]))
        tags.add(TBPM(encoding=3, text=["128"]))
        tags.add(TSRC(encoding=3, text=["DEA621200001"]))
        tags.add(TXXX(encoding=3, desc="replaygain_track_gain", text=["-7.5 dB"]))
        tags.add(TXXX(encoding=3, desc="MusicBrainz Album Id", text=["theirs-not-ours"]))
        tags.add(USLT(encoding=3, lang="eng", desc="", text="their own words"))
        tags.save(path)
    else:
        tags = FLAC(path)
        tags["composer"] = ["A composer"]
        tags["bpm"] = ["128"]
        tags["isrc"] = ["DEA621200001"]
        tags["replaygain_track_gain"] = ["-7.5 dB"]
        tags["musicbrainz_albumid"] = ["theirs-not-ours"]
        tags["lyrics"] = ["their own words"]
        tags.save()
    return path


@pytest.mark.parametrize("fixture", ["flac_file", "mp3_file"])
def test_intake_keeps_what_it_does_not_understand(fixture, request):
    """`keep_unknown` is the difference between taking a collection in and taking it apart."""
    path = with_history(request.getfixturevalue(fixture))
    plan = make_plan()
    plan.mbid = "ours-from-musicbrainz"

    tag_file(path, plan, plan.tracks[0], keep_unknown=True)

    if kind(path) == "mp3":
        tags = ID3(path)
        assert tags["TCOM"].text == ["A composer"] and tags["TBPM"].text == ["128"]
        assert tags["TSRC"].text == ["DEA621200001"]
        assert tags["TXXX:replaygain_track_gain"].text == ["-7.5 dB"]
        assert tags["TIT2"].text == ["T1"], "and the plan's own fields are written"
        assert tags["TXXX:MusicBrainz Album Id"].text == ["theirs-not-ours"]
        assert next(f for f in tags.values() if f.FrameID == "USLT").text == "their own words"
    else:
        tags = FLAC(path)
        assert tags["composer"] == ["A composer"] and tags["bpm"] == ["128"]
        assert tags["isrc"] == ["DEA621200001"]
        assert tags["replaygain_track_gain"] == ["-7.5 dB"]
        assert tags["title"] == ["T1"]
        assert tags["musicbrainz_albumid"] == ["theirs-not-ours"]
        assert tags["lyrics"] == ["their own words"]


@pytest.mark.parametrize("fixture", ["flac_file", "mp3_file"])
def test_without_it_the_plan_is_the_whole_truth(fixture, request):
    """A file we downloaded carries whatever yt-dlp put there and nothing worth keeping."""
    path = with_history(request.getfixturevalue(fixture))
    plan = make_plan()
    plan.mbid = "ours-from-musicbrainz"

    tag_file(path, plan, plan.tracks[0])

    if kind(path) == "mp3":
        tags = ID3(path)
        assert "TCOM" not in tags and "TSRC" not in tags
        assert tags["TXXX:MusicBrainz Album Id"].text == ["ours-from-musicbrainz"]
        assert not [f for f in tags.values() if f.FrameID == "USLT"]
    else:
        tags = FLAC(path)
        assert "composer" not in tags and "isrc" not in tags
        assert tags["musicbrainz_albumid"] == ["ours-from-musicbrainz"]
        assert "lyrics" not in tags


def test_intake_still_writes_words_into_a_file_that_has_none(flac_file):
    """Keeping theirs is not refusing to write ours — the rule is about a value that exists."""
    plan = make_plan()

    tag_file(flac_file, plan, plan.tracks[0], lyrics="ours", keep_unknown=True)

    assert tagged_lyrics(flac_file) == "ours"


def test_a_length_of_zero_is_unknown_and_not_a_short_track(tmp_path, monkeypatch):
    """Three albums in the reference collection are FLACs whose STREAMINFO says `total_samples = 0`.
    A 0 there is a gap the encoder never filled in, not a measurement — and read as a number it
    made 52 real tracks "shorter than 30s", which is how an intro card is recognised and dropped."""
    from noaap import tag

    path = tmp_path / "t.flac"
    path.write_bytes(b"not read: the info object is the thing under test")

    class Silent:
        info = type("info", (), {"length": 0.0})()

    monkeypatch.setattr(tag, "_open", lambda p: Silent())

    assert tag.audio_length(path) is None


def test_a_local_address_is_not_written_into_the_file(tmp_path):
    """`source` is there so whoever opens the file later can go back to where it came from. A
    folder's address is the user's own directory — it identifies the album to nobody, and putting
    it in every file carries a home path around. Found by reading the tags of a real intake."""
    from noaap.tag import build_tags

    plan = make_plan()
    plan.source_url = "/home/someone/Music/legacy/A Band/An Album"

    assert "source" not in build_tags(plan, plan.tracks[0])

    plan.source_url = "https://www.youtube.com/playlist?list=PLx"
    assert build_tags(plan, plan.tracks[0])["source"] == plan.source_url


def test_a_length_is_measured_once_and_the_same_way_everywhere(tmp_path, monkeypatch):
    """The acceptance run found 52 tracks with no `file_length` although their candidate held a
    decoded one: the download path read the header only. Every place that needs this file's own
    seconds — the plan's `file_length`, the LRCLIB match, the vendor's bill — asks the same
    function now, and `_measure_candidate` never trades a number it has for an absence."""
    from noaap import tag
    from noaap.download import _measure_candidate
    from noaap.models import Candidate, PlanTrack

    path = tmp_path / "t.flac"
    path.write_bytes(b"stands in for a file whose header will not answer")
    monkeypatch.setattr(tag, "audio_length", lambda p: None)
    monkeypatch.setattr(tag, "decoded_length", lambda p: 269.7)

    assert tag.measured_length(path) == 269.7

    track = PlanTrack(video_id="x", number=1, artist="A", title="t", filename="t.flac",
                      provenance={}, candidates=[Candidate(ref="x", length=269.7)], chosen="x")
    track.file_length = None
    _measure_candidate(track, path)

    assert track.candidate("x").length == 269.7, "a known length survives a file that will not say"


def _three_discs():
    """A plan whose discs are of different lengths, and whose numbers restart on each — which is
    what the user's own library does: 52 discs across 23 albums, numbered 1..n within the disc."""
    from noaap.models import AlbumPlan, Kind, PlanTrack

    tracks = [PlanTrack(video_id=f"v{d}{n}", number=n, artist="A", title=f"T{d}-{n}",
                        filename=f"{d}-{n}.x", provenance={}, disc=d)
              for d, many in ((1, 3), (2, 1), (3, 2)) for n in range(1, many + 1)]
    return AlbumPlan(source_url="https://www.youtube.com/playlist?list=PLx", source_id="PLx",
                     kind=Kind.OFFICIAL_ALBUM, album="Alles", albumartist="Aphelion", year=None,
                     cover_url=None, folder="x", tracks=tracks)


def test_a_track_total_is_the_count_of_its_own_disc(flac_file, mp3_file, m4a_file):
    """And the count of discs is a field of its own (§9, slice 102).

    All three writers used `len(plan.tracks)` — the whole album — so every track of a three-disc set
    said 29 of 29, and only the m4a writer ever said how many discs there were. Measured in the
    user's own library before the fix: **627 files across 23 albums**, every one of them wrong, and
    0 of 627 carrying a disc total at all. A single-disc album's two numbers are equal, which is why
    nothing noticed.
    """
    from mutagen.mp4 import MP4

    plan = _three_discs()
    second = next(t for t in plan.tracks if t.disc == 2)      # the only track on disc 2

    tag_file(flac_file, plan, second)
    assert FLAC(flac_file)["tracktotal"] == ["1"] and FLAC(flac_file)["totaltracks"] == ["1"]
    assert FLAC(flac_file)["disctotal"] == ["3"] and FLAC(flac_file)["totaldiscs"] == ["3"]

    tag_file(mp3_file, plan, second)
    assert ID3(mp3_file)["TRCK"].text == ["1/1"] and ID3(mp3_file)["TPOS"].text == ["2/3"]

    tag_file(m4a_file, plan, second)
    assert MP4(m4a_file)["trkn"] == [(1, 1)] and MP4(m4a_file)["disk"] == [(2, 3)]

    third = next(t for t in plan.tracks if t.disc == 3)       # a disc of two
    tag_file(flac_file, plan, third)
    assert FLAC(flac_file)["tracktotal"] == ["2"], "its own disc, not the album's nine"


def test_the_disc_totals_read_back_as_they_were_written(flac_file, mp3_file, m4a_file):
    """Which is the half that keeps the dry run honest (§9, slice 85).

    `TPOS` went through the key loop that reads a frame's whole text, so a file noaap had just
    written would come back with `discnumber` = "2/3" and be compared against "2" — and every pass
    would say, for ever, that it needs retagging.
    """
    from noaap.tag import tags_in

    plan = _three_discs()
    second = next(t for t in plan.tracks if t.disc == 2)
    for path in (flac_file, mp3_file, m4a_file):
        tag_file(path, plan, second)
        got = tags_in(path)
        assert (got["tracknumber"], got["tracktotal"], got["totaltracks"]) == ("1", "1", "1"), path.suffix
        assert (got["discnumber"], got["disctotal"], got["totaldiscs"]) == ("2", "3", "3"), path.suffix


def _disc_plan(shape, totals=None):
    """A plan whose discs hold the given track numbers, each file remembering `totals` as its own."""
    from noaap.models import AlbumPlan, Kind, PlanTrack

    tracks = []
    for disc, numbers in shape.items():
        for n in numbers:
            track = PlanTrack(video_id=f"v{disc}{n}", number=n, artist="A", title=f"T{disc}-{n}",
                              filename=f"{disc}-{n}.opus", provenance={}, disc=disc)
            if totals is not None and disc in totals:
                track.adopted_tags = {"tracktotal": [str(totals[disc])]}
            tracks.append(track)
    return AlbumPlan(source_url="https://www.youtube.com/playlist?list=PLx", source_id="PLx",
                     kind=Kind.OFFICIAL_ALBUM, album="Alles", albumartist="Aphelion", year=None,
                     cover_url=None, folder="x", tracks=tracks)


def test_a_disc_total_is_never_below_the_highest_number_on_it():
    """The user, on the count of tracks present: *"it could have track 10 of 9? that'd be odd"*.

    It could, and on 8 of the 52 discs in their own collection it would have. The five cases of the
    rule (R-346), in its order.
    """
    full = _disc_plan({1: [1, 2, 3], 2: [1, 2]})
    assert full.disc_length(1) == 3 and full.disc_length(2) == 2, "a full disc: count = highest"

    gapped = _disc_plan({1: [1, 2, 3], 2: [1, 3, 11]})
    assert gapped.disc_length(2) == 11, "no remembered total: the highest number, not the three present"

    remembered = _disc_plan({1: [1, 2, 3], 2: [1, 3, 11]}, totals={2: 12})
    assert remembered.disc_length(2) == 12, "every file said twelve, and twelve is credible: kept"

    disagree = _disc_plan({1: [1, 2, 3], 2: [1, 3, 11]})
    disagree.tracks[-1].adopted_tags = {"tracktotal": ["12"]}
    assert disagree.disc_length(2) == 11, "the files do not agree, so they are not evidence"

    impossible = _disc_plan({1: [1, 2, 3], 2: [1, 3, 11]}, totals={2: 3})
    assert impossible.disc_length(2) == 11, "three is below the highest number present: set aside"

    one_disc = _disc_plan({1: [1, 2, 3, 4]})
    assert one_disc.disc_length(1) == 4, "a single-disc album is unchanged"


def test_the_albums_own_length_is_not_evidence_about_a_disc():
    """Which is the one place the ordering cannot be read literally.

    Before this, noaap wrote the album's track count into every file — so for all 23 multi-disc
    albums in the user's collection "what every file already said" is the album's length: agreed by
    every track, not below any number, and wrong. Taking it would have left all 627 files as they are.
    """
    theirs = _disc_plan({1: [1, 2, 3], 2: [1, 2]}, totals={1: 5, 2: 5})   # five tracks in all
    assert theirs.disc_length(1) == 3 and theirs.disc_length(2) == 2

    # the same number, where it is *not* the album's length, is kept
    credible = _disc_plan({1: [1, 2, 3], 2: [1, 2]}, totals={1: 5})
    credible.tracks.append(credible.tracks[-1])          # six tracks now, so five means something
    assert credible.disc_length(1) == 5


def test_one_open_answers_everything_the_old_three_did(flac_file, mp3_file, opus_file, m4a_file):
    """Reading a file once must say exactly what reading it four times said (§9, slice 105).

    `read_tags`, `audio_length` and `audio_quality` each opened the file for themselves — four opens
    in all, two of them inside `audio_quality` — and a share re-reads on every one: a dry run of
    `take-in` over the user's own collection read **2.7 times the whole collection**, 80.75 GB for
    41 GB of music, where the dry run's own work is 2.3 MB of an album. The values may not move.
    """
    from noaap.sources_folder import measure, read_tags
    from noaap.tag import audio_length, audio_quality, reading

    plan = make_plan()
    for path in (flac_file, mp3_file, opus_file, m4a_file):
        tag_file(path, plan, plan.tracks[0], cover=JPEG)       # something in every field
        apart = (read_tags(path), audio_length(path), audio_quality(path))
        with reading(path) as one:
            together = (read_tags(path, one), audio_length(path, one), audio_quality(path, one))
        assert apart == together, path.suffix

        # and the measurement built on them, which is what an adoption records
        separately = measure(path, digest=False)
        with reading(path) as one:
            shared = measure(path, digest=False, one=one)
        assert separately == shared, path.suffix


def test_a_file_that_cannot_be_read_still_answers_nothing(tmp_path):
    """One open that fails must read as the old four did: no length, no quality, no tags, no raising."""
    from noaap.sources_folder import read_tags
    from noaap.tag import audio_length, audio_quality, reading

    broken = tmp_path / "not really.mp3"
    broken.write_bytes(b"this is not an mp3")
    with reading(broken) as one:
        assert audio_length(broken, one) is None
        assert audio_quality(broken, one) == {}
        assert read_tags(broken, one) == {}

    gone = tmp_path / "not there at all.flac"
    with reading(gone) as one:
        assert audio_length(gone, one) is None
        assert audio_quality(gone, one) == {}
        assert read_tags(gone, one) == {}
