"""FLAC and MP3: four containers, one vocabulary (DESIGN §9, slice 53).

Until 1.0.0 this program could read and write two of them. Everything that was not `.m4a` was
opened as Opus, so a `.flac` raised inside `audio_length`, was caught, and came back `None` — and a
`None` length reads as "no match" while an empty quality reads as "unknown". Nothing failed and no
test noticed, because no test had ever seen a FLAC. **That is the defect these cases exist for**,
and the first one fails against 1.0.0.

The files are generated by ffmpeg at test time; no audio lives in the repository.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest
from mutagen.flac import FLAC
from mutagen.id3 import ID3
from mutagen.mp3 import MP3
from test_media import JPEG, make_plan

from noaap.tag import audio_length, audio_quality, kind, tag_file, tagged_lyrics

SECOND = ["-f", "lavfi", "-i", "sine=duration=1"]


def encode(path: Path, *args: str) -> Path:
    if not shutil.which("ffmpeg"):
        pytest.skip("ffmpeg not installed")
    subprocess.run(["ffmpeg", "-v", "error", *SECOND, *args, str(path)], check=True)
    return path


@pytest.fixture
def flac_file(tmp_path) -> Path:
    return encode(tmp_path / "t.flac", "-c:a", "flac", "-ar", "44100", "-metadata", "title=junk")


@pytest.fixture
def mp3_file(tmp_path) -> Path:
    return encode(tmp_path / "t.mp3", "-c:a", "libmp3lame", "-b:a", "192k", "-metadata", "title=junk")


@pytest.fixture
def opus_file(tmp_path) -> Path:
    return encode(tmp_path / "t.opus", "-c:a", "libopus")


@pytest.fixture
def m4a_file(tmp_path) -> Path:
    return encode(tmp_path / "t.m4a", "-c:a", "aac", "-b:a", "128k")


# -- reading -------------------------------------------------------------------------------------


def test_a_flac_has_a_length_and_a_quality(flac_file):
    """The regression, stated as plainly as it deserves: this answered None and {}."""
    assert audio_length(flac_file) == pytest.approx(1.0, abs=0.1)

    quality = audio_quality(flac_file)
    assert quality["codec"] == "flac"
    assert quality["sample_rate"] == 44100 and quality["channels"] == 1
    assert quality["bitrate"] > 0


def test_an_mp3_has_a_length_and_a_quality(mp3_file):
    assert audio_length(mp3_file) == pytest.approx(1.0, abs=0.2)

    quality = audio_quality(mp3_file)
    assert quality["codec"] == "mp3"
    assert quality["sample_rate"] == 44100
    assert 150_000 < quality["bitrate"] < 210_000


@pytest.mark.parametrize("name,expected", [("a.opus", "opus"), ("a.flac", "flac"), ("a.mp3", "mp3"),
                                           ("a.m4a", "mp4"), ("a.mp4", "mp4"), ("a.MP3", "mp3"),
                                           ("a.weird", "opus")])
def test_the_container_is_decided_in_one_place(name, expected):
    """An unknown suffix still reads as Opus — that is what every download is, and guessing
    anything else would turn an odd name into an unreadable file."""
    assert kind(Path(name)) == expected


def test_every_container_measures(opus_file, flac_file, mp3_file, m4a_file):
    for path in (opus_file, flac_file, mp3_file, m4a_file):
        assert audio_length(path) is not None, path.suffix
        assert audio_quality(path).get("codec"), path.suffix


def test_something_that_is_not_audio_is_still_an_unknown_not_a_crash(tmp_path):
    not_audio = tmp_path / "sleeve.flac"
    not_audio.write_bytes(b"<html>a consent page</html>")

    assert audio_length(not_audio) is None
    assert audio_quality(not_audio) == {}


# -- writing -------------------------------------------------------------------------------------


def test_a_flac_is_tagged_and_carries_its_cover(flac_file):
    plan = make_plan()
    tag_file(flac_file, plan, plan.tracks[0], cover=JPEG)

    tags = FLAC(flac_file)
    assert tags["title"] == ["T1"] and tags["artist"] == ["A1"]
    assert tags["albumartist"] == ["My Dark Lullabies"]
    assert tags["album"] == ["Vol. 1 - Heavy Sleeping"]
    assert tags["tracknumber"] == ["1"] and tags["tracktotal"] == ["2"]
    assert tags["compilation"] == ["1"]
    assert len(tags.pictures) == 1 and tags.pictures[0].data == JPEG
    assert tags.pictures[0].type == 3


def test_an_mp3_is_tagged_and_carries_its_cover(mp3_file):
    plan = make_plan()
    tag_file(mp3_file, plan, plan.tracks[0], cover=JPEG)

    tags = ID3(mp3_file)
    assert tags["TIT2"].text == ["T1"] and tags["TPE1"].text == ["A1"]
    assert tags["TPE2"].text == ["My Dark Lullabies"]
    assert tags["TALB"].text == ["Vol. 1 - Heavy Sleeping"]
    assert tags["TRCK"].text == ["1/2"], "ID3 counts within the total, in one frame"
    assert tags["TCMP"].text == ["1"]
    assert tags["APIC:Cover"].data == JPEG
    assert tags["TXXX:source"].text == [plan.source_url], "not COMM: that is where people keep notes"


def test_a_disc_number_is_written_only_when_there_is_more_than_one(mp3_file, flac_file):
    one, many = make_plan(), make_plan(discs=2)

    tag_file(mp3_file, one, one.tracks[0])
    tag_file(flac_file, one, one.tracks[0])
    assert "TPOS" not in ID3(mp3_file) and "discnumber" not in FLAC(flac_file)

    tag_file(mp3_file, many, many.tracks[1])
    tag_file(flac_file, many, many.tracks[1])
    assert ID3(mp3_file)["TPOS"].text == ["2"] and FLAC(flac_file)["discnumber"] == ["2"]


def test_lyrics_are_written_and_read_back_in_both(flac_file, mp3_file):
    plan = make_plan()
    words = "[00:01.00] a line\n[00:02.00] and another"

    for path in (flac_file, mp3_file):
        tag_file(path, plan, plan.tracks[0], lyrics=words)
        assert tagged_lyrics(path) == words, path.suffix


# -- a file we did not make -----------------------------------------------------------------------


def with_history(path: Path) -> Path:
    """What a folder someone has been keeping looks like: fields this program does not model."""
    if kind(path) == "mp3":
        from mutagen.id3 import TBPM, TCOM, TSRC, TXXX, USLT
        tags = ID3(path) if MP3(path).tags else ID3()
        tags.add(TCOM(encoding=3, text=["A composer"]))
        tags.add(TBPM(encoding=3, text=["128"]))
        tags.add(TSRC(encoding=3, text=["DEA621200001"]))
        tags.add(TXXX(encoding=3, desc="replaygain_track_gain", text=["-7.5 dB"]))
        tags.add(TXXX(encoding=3, desc="MusicBrainz Album Id", text=["theirs-not-ours"]))
        tags.add(USLT(encoding=3, lang="eng", desc="", text="their own words"))
        tags.save(path)
    else:
        tags = FLAC(path)
        tags["composer"] = ["A composer"]
        tags["bpm"] = ["128"]
        tags["isrc"] = ["DEA621200001"]
        tags["replaygain_track_gain"] = ["-7.5 dB"]
        tags["musicbrainz_albumid"] = ["theirs-not-ours"]
        tags["lyrics"] = ["their own words"]
        tags.save()
    return path


@pytest.mark.parametrize("fixture", ["flac_file", "mp3_file"])
def test_intake_keeps_what_it_does_not_understand(fixture, request):
    """`keep_unknown` is the difference between taking a collection in and taking it apart."""
    path = with_history(request.getfixturevalue(fixture))
    plan = make_plan()
    plan.mbid = "ours-from-musicbrainz"

    tag_file(path, plan, plan.tracks[0], keep_unknown=True)

    if kind(path) == "mp3":
        tags = ID3(path)
        assert tags["TCOM"].text == ["A composer"] and tags["TBPM"].text == ["128"]
        assert tags["TSRC"].text == ["DEA621200001"]
        assert tags["TXXX:replaygain_track_gain"].text == ["-7.5 dB"]
        assert tags["TIT2"].text == ["T1"], "and the plan's own fields are written"
        assert tags["TXXX:MusicBrainz Album Id"].text == ["theirs-not-ours"]
        assert next(f for f in tags.values() if f.FrameID == "USLT").text == "their own words"
    else:
        tags = FLAC(path)
        assert tags["composer"] == ["A composer"] and tags["bpm"] == ["128"]
        assert tags["isrc"] == ["DEA621200001"]
        assert tags["replaygain_track_gain"] == ["-7.5 dB"]
        assert tags["title"] == ["T1"]
        assert tags["musicbrainz_albumid"] == ["theirs-not-ours"]
        assert tags["lyrics"] == ["their own words"]


@pytest.mark.parametrize("fixture", ["flac_file", "mp3_file"])
def test_without_it_the_plan_is_the_whole_truth(fixture, request):
    """A file we downloaded carries whatever yt-dlp put there and nothing worth keeping."""
    path = with_history(request.getfixturevalue(fixture))
    plan = make_plan()
    plan.mbid = "ours-from-musicbrainz"

    tag_file(path, plan, plan.tracks[0])

    if kind(path) == "mp3":
        tags = ID3(path)
        assert "TCOM" not in tags and "TSRC" not in tags
        assert tags["TXXX:MusicBrainz Album Id"].text == ["ours-from-musicbrainz"]
        assert not [f for f in tags.values() if f.FrameID == "USLT"]
    else:
        tags = FLAC(path)
        assert "composer" not in tags and "isrc" not in tags
        assert tags["musicbrainz_albumid"] == ["ours-from-musicbrainz"]
        assert "lyrics" not in tags


def test_intake_still_writes_words_into_a_file_that_has_none(flac_file):
    """Keeping theirs is not refusing to write ours — the rule is about a value that exists."""
    plan = make_plan()

    tag_file(flac_file, plan, plan.tracks[0], lyrics="ours", keep_unknown=True)

    assert tagged_lyrics(flac_file) == "ours"


def test_a_length_of_zero_is_unknown_and_not_a_short_track(tmp_path, monkeypatch):
    """Three albums in the reference collection are FLACs whose STREAMINFO says `total_samples = 0`.
    A 0 there is a gap the encoder never filled in, not a measurement — and read as a number it
    made 52 real tracks "shorter than 30s", which is how an intro card is recognised and dropped."""
    from noaap import tag

    path = tmp_path / "t.flac"
    path.write_bytes(b"not read: the info object is the thing under test")

    class Silent:
        info = type("info", (), {"length": 0.0})()

    monkeypatch.setattr(tag, "_open", lambda p: Silent())

    assert tag.audio_length(path) is None


def test_a_local_address_is_not_written_into_the_file(tmp_path):
    """`source` is there so whoever opens the file later can go back to where it came from. A
    folder's address is the user's own directory — it identifies the album to nobody, and putting
    it in every file carries a home path around. Found by reading the tags of a real intake."""
    from noaap.tag import build_tags

    plan = make_plan()
    plan.source_url = "/home/someone/Music/legacy/A Band/An Album"

    assert "source" not in build_tags(plan, plan.tracks[0])

    plan.source_url = "https://www.youtube.com/playlist?list=PLx"
    assert build_tags(plan, plan.tracks[0])["source"] == plan.source_url
